### ISSUE TITLE
Support python27 and add python27 tests.

### ISSUE THREAD

**Issue by laixintao** [laixintao/pingtop#20]
I am not sure if it is necessary to do this.

Give this issue a 👍if you want python2.7 support.

**Comment by ivanhercaz** [comment]
I am not really sure if it is going to worth to offer Python 2.7 support if we take in account that Python 2.7 has a few more months of life... or at least it won't be maintained officially. You can check the [Python 2.7 Countdown](https://pythonclock.org/).

For that reason I am going to :-1: this issue. I think you, developers with a lot of potential, might center your efforts in improve this, Pingtop, and another useful tools.

**Comment by laixintao** [comment]
Sorry, won't support :)
