### ISSUE TITLE
0.2.9 isn't in PyPI

### ISSUE THREAD

**Issue by ivanhercaz** [laixintao/pingtop#24]
I was going to make a pull request to solve the error message when you execute `pingtop` without commands because in 0.2.8 the message might be hard to understand that the error was to execute the program without commands.

However, I clone this repository and I check the solution is already applied! The problem is that it seems that version 0.2.9 [isn't availabe yet](https://pypi.org/project/pingtop/#history).

Could you solve it?

In addition I think you should have the README in RST format, but for that I am going to open a PR by myself.

**Comment by laixintao** [comment]
Hi Thanks for your #25 , ths pypi page looks good now: https://pypi.org/project/pingtop/

I forgot to upload v.0.2.9 thanks for reminding me, I uploaded v0.2.9 and release 0.2.11 with your changes. https://pypi.org/project/pingtop/#history

**Comment by ivanhercaz** [comment]
Nice! Thank you @laixintao :) Now everything looks fine.
