### ISSUE TITLE
Unknown distribution option

### ISSUE THREAD

**Issue by onewhitewolf** [laixintao/pingtop#31]
Hi at all,
I am trying to install pingtop, but i have this problem:

`root@kali:~/Scaricati/pingtop# python3 setup.py 
/usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'entry_points'
  warnings.warn(msg)
/usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
/usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied`

What about?

**Comment by laixintao** [comment]
Install pingtop from pip: https://github.com/laixintao/pingtop#install

Or from source code:
```
pip install -e .
```

Setup.py is not for installing.
