### ISSUE TITLE
pip install problem on version 0.2.14

### ISSUE THREAD

**Issue by ghost** [laixintao/pingtop#32]
When installing via pip install pingtop in virtualenv or default on macos, windows and linux I allways get:
`$ pingtop
Traceback (most recent call last):
  File "/home/adrian/.local/bin/pingtop", line 7, in <module>
    from pingtop import multi_ping
ModuleNotFoundError: No module named 'pingtop'`

If I install from source version 0.2.12 it works a bit until it crashes.

**Comment by laixintao** [comment]
I think it's a bug with packaging, sorry, I will fix it ASAP.

**Comment by laixintao** [comment]
Hi @hexterm 

I uploaded the version `v0.3.0` fix the package issue.

I tested in docker Python:3 installed pingtop successfully, please try install with:

```
pip install -U pingtop
```

Feel free to repoen this issue if you have futher questions.
