### ISSUE TITLE
Drop sudo need

### ISSUE THREAD

**Issue by laixintao** [laixintao/pingtop#5]
Replacement for RAW_SOCKET?

This tool need `sudo` because this:

https://github.com/laixintao/pingtop/blob/c8c522cfaa2622899d09e20b1046301936d38f5b/ping.py#L202

**Comment by ryankrage77** [comment]
If I run it with sudo, I get `command not found`, otherwise it fails.

**Comment by laixintao** [comment]
@ryankrage77 Did you install for current user only instead of installing globally?

Try type `which pingtop` and use absolute path to run:

```
sudo /usr/local/bin/pingtop xxx
```

(replace `/usr/local/bin/pingtop` with your absolute path.)

Or you can install for sudo user:

```
sudo pip install pingtop
```

**Comment by gzxultra** [comment]
no way to work around this, kernel will not allow sending of packets that cannot be trusted.

**Comment by sgowie** [comment]
If the python interpreter being invoked has been provided the appropriate capabilities, `sudo` is **not** required.

e.g.
```
$ pip install pingtop --user
$ NEWPATH=$(pwd)/.local/bin/python
$ cp $(which python) $NEWPATH
$ sudo setcap cap_net_raw=ep $NEWPATH
$ sed -i "1s;/usr/bin/python;$NEWPATH;" .local/bin/pingtop
```

This lets you run the installed pingtop without invoking sudo, and only the specific privileges required for pingtop to do its thing are granted.

```
$ .local/bin/pingtop google.ca cnn.com
```

**Comment by gzxultra** [comment]
@sgowie there is no `setcap` on OS X

**Comment by laixintao** [comment]
@gzxultra I am thinking support tcpping, if use tcpping do we still need `sudo` ?

**Comment by laixintao** [comment]
I will check BSD ping's source code, see how does it run without sudo.

**Comment by gzxultra** [comment]
@laixintao could you try this

https://apple.stackexchange.com/questions/312857/how-does-macos-allow-standard-users-to-ping#answer-312861

socket.SOCK_DGRAM in Python

**Comment by laixintao** [comment]
Solved by @gzxultra
